//kres_.write();
UPrimeTPrime.write();
ksgs_.write();
ktot_.write();
epres_.write();
epsgs_.write();
eptot_.write();
nu_.write();
LESResIndex.write();

turbDiff.write();
UUTSDF.write();
VVTSDF.write();
WWTSDF.write();
UVTSDF.write();
turbDiff_T.write();
UTTSDF.write();
VTTSDF.write();
WTTSDF.write();

turbDiss.write();
UUTSDP.write();
VVTSDP.write();
WWTSDP.write();
UVTSDP.write();
turbDiss_T_homo.write();
UTTSDP_homo.write();
VTTSDP_homo.write();
WTTSDP_homo.write();

turbDiss_homo.write();
UUTSDP_homo.write();
VVTSDP_homo.write();
WWTSDP_homo.write();
UVTSDP_homo.write();

pressDiff.write();
UUPVGC.write();
VVPVGC.write();
WWPVGC.write();
UVPVGC.write();
UTPVGC.write();
VTPVGC.write();
WTPVGC.write();

viscDiff.write();
UUMVD.write();
VVMVD.write();
WWMVD.write();
UVMVD.write();
viscDiff_homo.write();
UUMVD_homo.write();
VVMVD_homo.write();
WWMVD_homo.write();
UVMVD_homo.write();
viscDiff_T_homo.write();
UTMVD_homo.write();
VTMVD_homo.write();
WTMVD_homo.write();

kSmall.write();
